snippet:
  url:    /snippet/:slug
  param:  { module: snippet, action: show }
  
snippet_by_tag:
  url:    /tag/:tag
  param:  { module: snippet, action: listByTag }
  
snippet_by_autor:
  url:    /autor/:autor
  param:  { module: snippet, action: listByAutor }
  
novo:
  url:    /novo
  param:  { module: snippet, action: novo }
  
homepage:
  url:    /
  param:  { module: snippet, action: index }